name: "${project.name}"
version: "${project.version}"
api: ["2.0.0"]
authors: ["ScarletRedMan", "MEFRREEX"]
description: "Library for easy creating and handling of forms"
main: com.formconstructor.FormConstructor